[package]
name = "arcade_queue"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = ["Kaiyang Wu <self@origincode.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
